export const MockData = [
  { source:"ADA News", time:"2h ago", cats:["REGULATIONS","CLINICAL"],
    title:"ADA releases updated infection-control guidance for 2026 in response to evolving aerosol research",
    desc:"The American Dental Association has issued revised infection-control protocols emphasizing high-volume evacuation and N95 use during aerosol-generating procedures. The 14-page update consolidates eight separate advisories from the past three years and takes effect July 1, 2026.",
    reads:"3,127", status:"removed" },
  { source:"Inside Dentistry", time:"3h ago", cats:["TECHNOLOGY","CLINICAL"],
    title:"AI-assisted caries detection clears 510(k) hurdle, expected in chairside units by Q4",
    desc:"VistaCheck's deep-learning module received FDA clearance after a 12,000-image multi-site study showed 94% sensitivity for proximal lesions. Three major chairside imaging vendors have signaled integration plans before the end of the year.",
    reads:"2,104", status:"live" },
  { source:"DentistryIQ", time:"4h ago", cats:["HYGIENE","BUSINESS"],
    title:"Survey: 62% of hygienists report burnout symptoms, up six points year-over-year",
    desc:"RDH Magazine's annual workforce survey of 4,200 dental hygienists shows the steepest year-over-year burnout climb on record. Schedule density and ergonomic strain top the list of contributing factors, ahead of compensation.",
    reads:"1,820", status:"live" },
  { source:"Dental Products Hopper", time:"5h ago", cats:["PRODUCTS","TECHNOLOGY"],
    title:"3Shape ships TRIOS 6 with on-scanner AI bite analysis and Wi-Fi 7",
    desc:"The newest TRIOS adds a real-time occlusion heat-map and a 30% faster scan path. Pricing starts at $34,500 with trade-in credit for existing TRIOS 4/5 units; first deliveries are scheduled for late June.",
    reads:"1,455", status:"live" },
  { source:"Decisions in Dentistry", time:"6h ago", cats:["CLINICAL","REGULATIONS"],
    title:"Silver diamine fluoride coverage expands to 24 state Medicaid programs",
    desc:"A Pew Trust analysis published this morning shows SDF reimbursement now reaches 24 state programs, up from 17 last year. Pediatric utilization in covered states is averaging 3.4× pre-coverage rates.",
    reads:"1,189", status:"live" },
];